[package]
name = "roading"
version = "0.0.2-pre-alpha"
edition = "2021"

[build-dependencies]
cc = "1.0"

[dependencies]
x86_64 = "0.15.4"

[profile.dev]
panic = "abort"


[profile.release]
panic = "abort"
