[package]
name = "obsidian-kernel"
version = "0.0.3-pre-alpha"
edition = "2021"

[build-dependencies]
cc = "1.0"

[dependencies]
x86_64 = "0.15.4"
linked_list_allocator = "0.10"
spin = "0.10.0"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
