[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
linker = "ld.lld"
rustflags = [
  "-C", "relocation-model=static",
  "-C", "link-arg=-nostdlib",
  "-C", "link-arg=-no-pie",
  "-C", "opt-level=z", # menor tamanho
  "-C", "code-model=kernel",
  "-C", "link-arg=-Tlinker.ld",
]
